"""Create core tables

Revision ID: 5a0c7910ada6
Revises:
Create Date: 2026-09-05 21:49:16.676809
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "5a0c7910ada6"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # gen_random_uuid() lives in pgcrypto (docs/SCHEMA.sql).
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audio_assets",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("storage_key", sa.Text(), nullable=False),
        sa.Column("mime_type", sa.Text(), nullable=False),
        sa.Column("format", sa.Text(), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("sha256", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "format IN ('mp3', 'wav', 'opus', 'aac', 'flac', 'pcm')",
            name="ck_audio_assets_format",
        ),
        sa.CheckConstraint("duration_ms >= 0", name="ck_audio_assets_duration"),
        sa.CheckConstraint("size_bytes >= 0", name="ck_audio_assets_size"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("storage_key"),
    )
    op.create_index("idx_audio_assets_sha256", "audio_assets", ["sha256"], unique=False)
    op.create_table(
        "voices",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("provider", sa.Text(), nullable=False),
        sa.Column("provider_voice_id", sa.Text(), nullable=False),
        sa.Column("provider_model_hint", sa.Text(), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("language", sa.Text(), server_default="en", nullable=False),
        sa.Column("locale", sa.Text(), nullable=True),
        sa.Column("accent", sa.Text(), nullable=True),
        sa.Column("gender", sa.Text(), server_default="unknown", nullable=False),
        sa.Column("age_group", sa.Text(), server_default="unknown", nullable=False),
        sa.Column(
            "style_tags",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("preview_url", sa.Text(), nullable=True),
        sa.Column("enabled", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "age_group IN ('young', 'adult', 'mature', 'unknown')",
            name="ck_voices_age_group",
        ),
        sa.CheckConstraint(
            "gender IN ('female', 'male', 'neutral', 'unknown')",
            name="ck_voices_gender",
        ),
        sa.CheckConstraint(
            "provider IN ('openai', 'azure', 'elevenlabs', 'kokoro', 'macos_say')",
            name="ck_voices_provider",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "provider", "provider_voice_id", name="uq_voices_provider_id"
        ),
    )
    op.create_index("idx_voices_accent", "voices", ["accent"], unique=False)
    op.create_index("idx_voices_enabled", "voices", ["enabled"], unique=False)
    op.create_index("idx_voices_gender", "voices", ["gender"], unique=False)
    op.create_index("idx_voices_language", "voices", ["language"], unique=False)
    op.create_index("idx_voices_provider", "voices", ["provider"], unique=False)
    op.create_table(
        "projects",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("mode", sa.Text(), nullable=False),
        sa.Column("source_text", sa.Text(), server_default="", nullable=False),
        sa.Column(
            "transcript_visible_default",
            sa.Boolean(),
            server_default="true",
            nullable=False,
        ),
        sa.Column("default_voice_id", sa.UUID(), nullable=True),
        sa.Column(
            "default_generation_speed",
            sa.Numeric(precision=6, scale=3),
            server_default="1.0",
            nullable=False,
        ),
        sa.Column(
            "sentence_pause_ms", sa.Integer(), server_default="250", nullable=False
        ),
        sa.Column(
            "paragraph_pause_ms", sa.Integer(), server_default="600", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "mode IN ('monologue', 'dialogue', 'listening_test', 'shadowing')",
            name="ck_projects_mode",
        ),
        sa.ForeignKeyConstraint(
            ["default_voice_id"],
            ["voices.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tts_cache",
        sa.Column("cache_key", sa.String(), nullable=False),
        sa.Column("provider", sa.Text(), nullable=False),
        sa.Column("model", sa.Text(), nullable=True),
        sa.Column("provider_voice_id", sa.Text(), nullable=False),
        sa.Column("normalized_text_hash", sa.Text(), nullable=False),
        sa.Column("instructions_hash", sa.Text(), nullable=True),
        sa.Column("speed", sa.Numeric(precision=6, scale=3), nullable=False),
        sa.Column("output_format", sa.Text(), nullable=False),
        sa.Column("audio_asset_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_used_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["audio_asset_id"], ["audio_assets.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("cache_key"),
    )
    op.create_table(
        "render_jobs",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.Text(), server_default="queued", nullable=False),
        sa.Column("progress", sa.Integer(), server_default="0", nullable=False),
        sa.Column("output_format", sa.Text(), server_default="mp3", nullable=False),
        sa.Column("idempotency_key", sa.Text(), nullable=True),
        sa.Column("final_audio_asset_id", sa.UUID(), nullable=True),
        sa.Column("error_code", sa.Text(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('queued', 'running', 'completed', 'failed', 'cancelled')",
            name="ck_render_jobs_status",
        ),
        sa.CheckConstraint(
            "progress >= 0 AND progress <= 100", name="ck_render_jobs_progress"
        ),
        sa.ForeignKeyConstraint(
            ["final_audio_asset_id"], ["audio_assets.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_render_jobs_idem",
        "render_jobs",
        ["project_id", "idempotency_key"],
        unique=True,
        postgresql_where=sa.text("idempotency_key IS NOT NULL"),
    )
    op.create_index(
        "idx_render_jobs_project", "render_jobs", ["project_id"], unique=False
    )
    op.create_index("idx_render_jobs_status", "render_jobs", ["status"], unique=False)
    op.create_table(
        "speakers",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("label", sa.Text(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column("voice_id", sa.UUID(), nullable=True),
        sa.Column(
            "generation_speed",
            sa.Numeric(precision=6, scale=3),
            server_default="1.0",
            nullable=False,
        ),
        sa.Column(
            "default_pause_before_ms", sa.Integer(), server_default="0", nullable=False
        ),
        sa.Column(
            "default_pause_after_ms", sa.Integer(), server_default="250", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "default_pause_after_ms >= 0", name="ck_speakers_pause_after"
        ),
        sa.CheckConstraint(
            "default_pause_before_ms >= 0", name="ck_speakers_pause_before"
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["voice_id"],
            ["voices.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "label", name="uq_speakers_project_label"),
    )
    op.create_table(
        "segments",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("speaker_id", sa.UUID(), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("voice_id_override", sa.UUID(), nullable=True),
        sa.Column(
            "generation_speed_override", sa.Numeric(precision=6, scale=3), nullable=True
        ),
        sa.Column("pause_before_ms", sa.Integer(), server_default="0", nullable=False),
        sa.Column("pause_after_ms", sa.Integer(), server_default="250", nullable=False),
        sa.Column("audio_asset_id", sa.UUID(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("order_index >= 0", name="ck_segments_order_index"),
        sa.CheckConstraint("pause_after_ms >= 0", name="ck_segments_pause_after"),
        sa.CheckConstraint("pause_before_ms >= 0", name="ck_segments_pause_before"),
        sa.ForeignKeyConstraint(
            ["audio_asset_id"], ["audio_assets.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["speaker_id"], ["speakers.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["voice_id_override"],
            ["voices.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "project_id", "order_index", name="uq_segments_project_order"
        ),
    )
    op.create_index(
        "idx_segments_project_order",
        "segments",
        ["project_id", "order_index"],
        unique=False,
    )
    op.create_index("idx_segments_speaker", "segments", ["speaker_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_segments_speaker", table_name="segments")
    op.drop_index("idx_segments_project_order", table_name="segments")
    op.drop_table("segments")
    op.drop_table("speakers")
    op.drop_index("idx_render_jobs_status", table_name="render_jobs")
    op.drop_index("idx_render_jobs_project", table_name="render_jobs")
    op.drop_index(
        "idx_render_jobs_idem",
        table_name="render_jobs",
        postgresql_where=sa.text("idempotency_key IS NOT NULL"),
    )
    op.drop_table("render_jobs")
    op.drop_table("tts_cache")
    op.drop_table("projects")
    op.drop_index("idx_voices_provider", table_name="voices")
    op.drop_index("idx_voices_language", table_name="voices")
    op.drop_index("idx_voices_gender", table_name="voices")
    op.drop_index("idx_voices_enabled", table_name="voices")
    op.drop_index("idx_voices_accent", table_name="voices")
    op.drop_table("voices")
    op.drop_index("idx_audio_assets_sha256", table_name="audio_assets")
    op.drop_table("audio_assets")
    # ### end Alembic commands ###
