"""Add repeat settings

Revision ID: 9e385d19ebf1
Revises: b1c4e77a90d2
Create Date: 2026-09-06 00:45:14.916223
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "9e385d19ebf1"
down_revision: str | None = "b1c4e77a90d2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects",
        sa.Column("repeat_count", sa.Integer(), server_default="1", nullable=False),
    )
    op.add_column(
        "projects",
        sa.Column(
            "pause_between_repeats_ms",
            sa.Integer(),
            server_default="3000",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "pause_between_repeats_ms")
    op.drop_column("projects", "repeat_count")
    # ### end Alembic commands ###
