"""Add users and project ownership

Revision ID: fd79b6e25428
Revises: 9e385d19ebf1
Create Date: 2026-09-06 01:59:41.998528
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "fd79b6e25428"
down_revision: str | None = "9e385d19ebf1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("auth_provider", sa.Text(), nullable=False),
        sa.Column("provider_account_id", sa.Text(), nullable=False),
        sa.Column("email", sa.Text(), nullable=True),
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column("avatar_url", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "auth_provider IN ('google', 'x')", name="ck_users_auth_provider"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "auth_provider", "provider_account_id", name="uq_users_provider_account"
        ),
    )
    op.create_index("idx_users_email", "users", ["email"], unique=False)
    op.add_column("projects", sa.Column("user_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        None, "projects", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "projects", type_="foreignkey")
    op.drop_column("projects", "user_id")
    op.drop_index("idx_users_email", table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
